"use client";
import {useState} from 'react';
import {ArrowUp,X,Loader2,Sparkles,FileText} from 'lucide-react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
export default function SearchBar({onActivity,onSource}){
 const [query,setQuery]=useState(''),[result,setResult]=useState(null),[history,setHistory]=useState([]),[currentQuestion,setCurrentQuestion]=useState(''),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[status,setStatus]=useState(''),[sources,setSources]=useState([]);
 async function submit(e){e.preventDefault();if(!query.trim()||loading)return;const submitted=query.trim();setCurrentQuestion(submitted);setLoading(true);setOpen(false);setSources([]);onActivity([]);setStatus('Conectando neuronas…');
 try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify({message:query,history})});
 let answer;
 if(res.headers.get('content-type')?.includes('ndjson')){const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines.filter(Boolean)){const event=JSON.parse(line);if(event.type==='progress'){setStatus(event.label);if(event.files)onActivity(event.files);}if(event.type==='result')answer=event.data;}if(done)break;}}
 else answer=await res.json();
 if(!answer)throw Error('empty');setResult(answer.reply||'No se obtuvo una respuesta.');setSources(answer.sources||[]);onActivity(answer.sources||[]);setOpen(true);if(!answer.error&&res.ok)setHistory(h=>[...h,{role:'user',content:submitted},{role:'assistant',content:answer.reply}].slice(-6));
 }catch{setResult('No se pudo completar la conexión. Inténtalo otra vez.');setOpen(true);onActivity([]);}finally{setLoading(false);setStatus('');}}
 const questions=history.filter(item=>item.role==='user').map(item=>item.content);if(currentQuestion&&!questions.includes(currentQuestion))questions.push(currentQuestion);
 return <section className={`search-dock ${open?'chat-open':''}`}>{open&&<article className="answer-card"><header><span><Sparkles size={15}/> CONVERSACIÓN DEL CEREBRO</span><button onClick={()=>{setOpen(false);setResult(null);setSources([]);setCurrentQuestion('');onActivity([]);}} aria-label="Cerrar conversación"><X size={18}/></button></header><div className="chat-history">{questions.map((question,i)=><div key={`q-${i}`} className="chat-pair"><div className="chat-bubble user-bubble">{question}</div>{i===questions.length-1&&result&&<div className="chat-bubble brain-bubble"><div className="answer-body prose-brain"><Markdown remarkPlugins={[remarkGfm]}>{result}</Markdown></div></div>}</div>)}</div>{sources.length>0&&<footer><span className="source-label">FUENTES CONSULTADAS</span>{sources.map(id=><button key={id} onClick={()=>onSource(id)}><FileText size={12}/>{id.split('/').pop()}</button>)}</footer>}<button className="new-query" onClick={()=>{setOpen(false);setQuery('');setResult(null);setSources([]);setCurrentQuestion('');setHistory([]);onActivity([]);}}>Nueva consulta</button></article>}
 <form className={`neural-search ${loading?'is-loading':''}`} onSubmit={submit}><span className="search-symbol">{loading?<Loader2 className="animate-spin" size={21}/>:<Sparkles size={21}/>}</span><div className="search-field"><label htmlFor="brain-question">{loading?status:'PREGÚNTALE A BOGATI BRAIN'}</label><input id="brain-question" value={query} onChange={e=>setQuery(e.target.value)} disabled={loading} placeholder="¿Qué quieres descubrir hoy?" maxLength={1000}/></div><button type="submit" disabled={loading||!query.trim()} aria-label="Enviar pregunta"><ArrowUp size={22}/></button></form><p className="search-footnote">Conocimiento de Bogati · Respuestas conectadas a tus archivos</p></section>;
}
